// Generated by createDBTableBinds() function

#include "_generated/mybankBinds.h"

Binds<InputCType> bank_accountInputBinds() {
    return Binds<InputCType>( make_vector<InputCType>(
        std::make_unique<TypeInputImpl<int, MYSQL_TYPE_LONG>>( "acc_no" ),
        std::make_unique<TypeCharArrayInput>( "fname", MYSQL_TYPE_STRING, 100 ),
        std::make_unique<TypeCharArrayInput>( "lname", MYSQL_TYPE_STRING, 100 ),
        std::make_unique<TypeInputImpl<double, MYSQL_TYPE_DOUBLE>>( "balance" ) ) );
}
Binds<OutputCType> bank_accountOutputBinds() {
    return Binds<OutputCType>( make_vector<OutputCType>(
        std::make_unique<TypeOutputImpl<int, MYSQL_TYPE_LONG>>( "acc_no" ),
        std::make_unique<TypeCharArrayOutput>( "fname", MYSQL_TYPE_VAR_STRING, 100 ),
        std::make_unique<TypeCharArrayOutput>( "lname", MYSQL_TYPE_VAR_STRING, 100 ),
        std::make_unique<TypeCharArrayOutput>( "balance", MYSQL_TYPE_NEWDECIMAL, 100 ) ) );
}
