# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sethvan/Documents/dev/projects/seth_ql

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sethvan/Documents/dev/projects/seth_ql

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sethvan/Documents/dev/projects/seth_ql/CMakeFiles /home/sethvan/Documents/dev/projects/seth_ql//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sethvan/Documents/dev/projects/seth_ql/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named seth_ql

# Build rule for target.
seth_ql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 seth_ql
.PHONY : seth_ql

# fast build rule for target.
seth_ql/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/build
.PHONY : seth_ql/fast

src/binds_array_wrapper/SqlTypes.o: src/binds_array_wrapper/SqlTypes.cpp.o
.PHONY : src/binds_array_wrapper/SqlTypes.o

# target to build an object file
src/binds_array_wrapper/SqlTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/binds_array_wrapper/SqlTypes.cpp.o
.PHONY : src/binds_array_wrapper/SqlTypes.cpp.o

src/binds_array_wrapper/SqlTypes.i: src/binds_array_wrapper/SqlTypes.cpp.i
.PHONY : src/binds_array_wrapper/SqlTypes.i

# target to preprocess a source file
src/binds_array_wrapper/SqlTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/binds_array_wrapper/SqlTypes.cpp.i
.PHONY : src/binds_array_wrapper/SqlTypes.cpp.i

src/binds_array_wrapper/SqlTypes.s: src/binds_array_wrapper/SqlTypes.cpp.s
.PHONY : src/binds_array_wrapper/SqlTypes.s

# target to generate assembly for a file
src/binds_array_wrapper/SqlTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/binds_array_wrapper/SqlTypes.cpp.s
.PHONY : src/binds_array_wrapper/SqlTypes.cpp.s

src/binds_array_wrapper/utilities.o: src/binds_array_wrapper/utilities.cpp.o
.PHONY : src/binds_array_wrapper/utilities.o

# target to build an object file
src/binds_array_wrapper/utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/binds_array_wrapper/utilities.cpp.o
.PHONY : src/binds_array_wrapper/utilities.cpp.o

src/binds_array_wrapper/utilities.i: src/binds_array_wrapper/utilities.cpp.i
.PHONY : src/binds_array_wrapper/utilities.i

# target to preprocess a source file
src/binds_array_wrapper/utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/binds_array_wrapper/utilities.cpp.i
.PHONY : src/binds_array_wrapper/utilities.cpp.i

src/binds_array_wrapper/utilities.s: src/binds_array_wrapper/utilities.cpp.s
.PHONY : src/binds_array_wrapper/utilities.s

# target to generate assembly for a file
src/binds_array_wrapper/utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/binds_array_wrapper/utilities.cpp.s
.PHONY : src/binds_array_wrapper/utilities.cpp.s

src/create_db_table_binds/createDBTableBinds.o: src/create_db_table_binds/createDBTableBinds.cpp.o
.PHONY : src/create_db_table_binds/createDBTableBinds.o

# target to build an object file
src/create_db_table_binds/createDBTableBinds.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/create_db_table_binds/createDBTableBinds.cpp.o
.PHONY : src/create_db_table_binds/createDBTableBinds.cpp.o

src/create_db_table_binds/createDBTableBinds.i: src/create_db_table_binds/createDBTableBinds.cpp.i
.PHONY : src/create_db_table_binds/createDBTableBinds.i

# target to preprocess a source file
src/create_db_table_binds/createDBTableBinds.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/create_db_table_binds/createDBTableBinds.cpp.i
.PHONY : src/create_db_table_binds/createDBTableBinds.cpp.i

src/create_db_table_binds/createDBTableBinds.s: src/create_db_table_binds/createDBTableBinds.cpp.s
.PHONY : src/create_db_table_binds/createDBTableBinds.s

# target to generate assembly for a file
src/create_db_table_binds/createDBTableBinds.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/create_db_table_binds/createDBTableBinds.cpp.s
.PHONY : src/create_db_table_binds/createDBTableBinds.cpp.s

src/create_db_table_binds/getDBTables.o: src/create_db_table_binds/getDBTables.cpp.o
.PHONY : src/create_db_table_binds/getDBTables.o

# target to build an object file
src/create_db_table_binds/getDBTables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/create_db_table_binds/getDBTables.cpp.o
.PHONY : src/create_db_table_binds/getDBTables.cpp.o

src/create_db_table_binds/getDBTables.i: src/create_db_table_binds/getDBTables.cpp.i
.PHONY : src/create_db_table_binds/getDBTables.i

# target to preprocess a source file
src/create_db_table_binds/getDBTables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/create_db_table_binds/getDBTables.cpp.i
.PHONY : src/create_db_table_binds/getDBTables.cpp.i

src/create_db_table_binds/getDBTables.s: src/create_db_table_binds/getDBTables.cpp.s
.PHONY : src/create_db_table_binds/getDBTables.s

# target to generate assembly for a file
src/create_db_table_binds/getDBTables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/create_db_table_binds/getDBTables.cpp.s
.PHONY : src/create_db_table_binds/getDBTables.cpp.s

src/other_mysql_wrappers/MySQLSession.o: src/other_mysql_wrappers/MySQLSession.cpp.o
.PHONY : src/other_mysql_wrappers/MySQLSession.o

# target to build an object file
src/other_mysql_wrappers/MySQLSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/MySQLSession.cpp.o
.PHONY : src/other_mysql_wrappers/MySQLSession.cpp.o

src/other_mysql_wrappers/MySQLSession.i: src/other_mysql_wrappers/MySQLSession.cpp.i
.PHONY : src/other_mysql_wrappers/MySQLSession.i

# target to preprocess a source file
src/other_mysql_wrappers/MySQLSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/MySQLSession.cpp.i
.PHONY : src/other_mysql_wrappers/MySQLSession.cpp.i

src/other_mysql_wrappers/MySQLSession.s: src/other_mysql_wrappers/MySQLSession.cpp.s
.PHONY : src/other_mysql_wrappers/MySQLSession.s

# target to generate assembly for a file
src/other_mysql_wrappers/MySQLSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/MySQLSession.cpp.s
.PHONY : src/other_mysql_wrappers/MySQLSession.cpp.s

src/other_mysql_wrappers/Query.o: src/other_mysql_wrappers/Query.cpp.o
.PHONY : src/other_mysql_wrappers/Query.o

# target to build an object file
src/other_mysql_wrappers/Query.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/Query.cpp.o
.PHONY : src/other_mysql_wrappers/Query.cpp.o

src/other_mysql_wrappers/Query.i: src/other_mysql_wrappers/Query.cpp.i
.PHONY : src/other_mysql_wrappers/Query.i

# target to preprocess a source file
src/other_mysql_wrappers/Query.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/Query.cpp.i
.PHONY : src/other_mysql_wrappers/Query.cpp.i

src/other_mysql_wrappers/Query.s: src/other_mysql_wrappers/Query.cpp.s
.PHONY : src/other_mysql_wrappers/Query.s

# target to generate assembly for a file
src/other_mysql_wrappers/Query.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/Query.cpp.s
.PHONY : src/other_mysql_wrappers/Query.cpp.s

src/other_mysql_wrappers/Statement.o: src/other_mysql_wrappers/Statement.cpp.o
.PHONY : src/other_mysql_wrappers/Statement.o

# target to build an object file
src/other_mysql_wrappers/Statement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/Statement.cpp.o
.PHONY : src/other_mysql_wrappers/Statement.cpp.o

src/other_mysql_wrappers/Statement.i: src/other_mysql_wrappers/Statement.cpp.i
.PHONY : src/other_mysql_wrappers/Statement.i

# target to preprocess a source file
src/other_mysql_wrappers/Statement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/Statement.cpp.i
.PHONY : src/other_mysql_wrappers/Statement.cpp.i

src/other_mysql_wrappers/Statement.s: src/other_mysql_wrappers/Statement.cpp.s
.PHONY : src/other_mysql_wrappers/Statement.s

# target to generate assembly for a file
src/other_mysql_wrappers/Statement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/Statement.cpp.s
.PHONY : src/other_mysql_wrappers/Statement.cpp.s

src/other_mysql_wrappers/common.o: src/other_mysql_wrappers/common.cpp.o
.PHONY : src/other_mysql_wrappers/common.o

# target to build an object file
src/other_mysql_wrappers/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/common.cpp.o
.PHONY : src/other_mysql_wrappers/common.cpp.o

src/other_mysql_wrappers/common.i: src/other_mysql_wrappers/common.cpp.i
.PHONY : src/other_mysql_wrappers/common.i

# target to preprocess a source file
src/other_mysql_wrappers/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/common.cpp.i
.PHONY : src/other_mysql_wrappers/common.cpp.i

src/other_mysql_wrappers/common.s: src/other_mysql_wrappers/common.cpp.s
.PHONY : src/other_mysql_wrappers/common.s

# target to generate assembly for a file
src/other_mysql_wrappers/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seth_ql.dir/build.make CMakeFiles/seth_ql.dir/src/other_mysql_wrappers/common.cpp.s
.PHONY : src/other_mysql_wrappers/common.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... seth_ql"
	@echo "... src/binds_array_wrapper/SqlTypes.o"
	@echo "... src/binds_array_wrapper/SqlTypes.i"
	@echo "... src/binds_array_wrapper/SqlTypes.s"
	@echo "... src/binds_array_wrapper/utilities.o"
	@echo "... src/binds_array_wrapper/utilities.i"
	@echo "... src/binds_array_wrapper/utilities.s"
	@echo "... src/create_db_table_binds/createDBTableBinds.o"
	@echo "... src/create_db_table_binds/createDBTableBinds.i"
	@echo "... src/create_db_table_binds/createDBTableBinds.s"
	@echo "... src/create_db_table_binds/getDBTables.o"
	@echo "... src/create_db_table_binds/getDBTables.i"
	@echo "... src/create_db_table_binds/getDBTables.s"
	@echo "... src/other_mysql_wrappers/MySQLSession.o"
	@echo "... src/other_mysql_wrappers/MySQLSession.i"
	@echo "... src/other_mysql_wrappers/MySQLSession.s"
	@echo "... src/other_mysql_wrappers/Query.o"
	@echo "... src/other_mysql_wrappers/Query.i"
	@echo "... src/other_mysql_wrappers/Query.s"
	@echo "... src/other_mysql_wrappers/Statement.o"
	@echo "... src/other_mysql_wrappers/Statement.i"
	@echo "... src/other_mysql_wrappers/Statement.s"
	@echo "... src/other_mysql_wrappers/common.o"
	@echo "... src/other_mysql_wrappers/common.i"
	@echo "... src/other_mysql_wrappers/common.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

