// This file was generated by createDBTableBinds() function
#ifndef INCLUDED_MYBANKBINDS_H
#define INCLUDED_MYBANKBINDS_H

#include "binds.hpp"


Binds<InputCType> bank_accountInputBinds();
Binds<OutputCType> bank_accountOutputBinds();

#endif //INCLUDED_MYBANKBINDS_H
