// This file was generated by createDBTableBinds() function
#ifndef INCLUDED_GIRRAFEBINDS_H
#define INCLUDED_GIRRAFEBINDS_H

#include "BindsArray.hpp"
#include "makeBinds.hpp"

using namespace seth_ql;

BindsArray<InputCType> branchInputBindsArray();
BindsArray<OutputCType> branchOutputBindsArray();

BindsArray<InputCType> branch_supplierInputBindsArray();
BindsArray<OutputCType> branch_supplierOutputBindsArray();

BindsArray<InputCType> clientInputBindsArray();
BindsArray<OutputCType> clientOutputBindsArray();

BindsArray<InputCType> employeeInputBindsArray();
BindsArray<OutputCType> employeeOutputBindsArray();

BindsArray<InputCType> works_withInputBindsArray();
BindsArray<OutputCType> works_withOutputBindsArray();

#endif  // INCLUDED_GIRRAFEBINDS_H
