// This file was generated by createDBTableBinds() function
#ifndef INCLUDED_PERFORMANCE_SCHEMABINDS_H
#define INCLUDED_PERFORMANCE_SCHEMABINDS_H

#include "BindsArray.hpp"
#include "makeBinds.hpp"

using namespace seth_ql;

BindsArray<InputCType> accountsInputBindsArray();
BindsArray<OutputCType> accountsOutputBindsArray();

BindsArray<InputCType> cond_instancesInputBindsArray();
BindsArray<OutputCType> cond_instancesOutputBindsArray();

BindsArray<InputCType> events_stages_currentInputBindsArray();
BindsArray<OutputCType> events_stages_currentOutputBindsArray();

BindsArray<InputCType> events_stages_historyInputBindsArray();
BindsArray<OutputCType> events_stages_historyOutputBindsArray();

BindsArray<InputCType> events_stages_history_longInputBindsArray();
BindsArray<OutputCType> events_stages_history_longOutputBindsArray();

BindsArray<InputCType> events_stages_summary_by_account_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_stages_summary_by_account_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_stages_summary_by_host_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_stages_summary_by_host_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_stages_summary_by_thread_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_stages_summary_by_thread_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_stages_summary_by_user_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_stages_summary_by_user_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_stages_summary_global_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_stages_summary_global_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_statements_currentInputBindsArray();
BindsArray<OutputCType> events_statements_currentOutputBindsArray();

BindsArray<InputCType> events_statements_historyInputBindsArray();
BindsArray<OutputCType> events_statements_historyOutputBindsArray();

BindsArray<InputCType> events_statements_history_longInputBindsArray();
BindsArray<OutputCType> events_statements_history_longOutputBindsArray();

BindsArray<InputCType> events_statements_summary_by_account_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_statements_summary_by_account_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_statements_summary_by_digestInputBindsArray();
BindsArray<OutputCType> events_statements_summary_by_digestOutputBindsArray();

BindsArray<InputCType> events_statements_summary_by_host_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_statements_summary_by_host_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_statements_summary_by_programInputBindsArray();
BindsArray<OutputCType> events_statements_summary_by_programOutputBindsArray();

BindsArray<InputCType> events_statements_summary_by_thread_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_statements_summary_by_thread_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_statements_summary_by_user_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_statements_summary_by_user_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_statements_summary_global_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_statements_summary_global_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_transactions_currentInputBindsArray();
BindsArray<OutputCType> events_transactions_currentOutputBindsArray();

BindsArray<InputCType> events_transactions_historyInputBindsArray();
BindsArray<OutputCType> events_transactions_historyOutputBindsArray();

BindsArray<InputCType> events_transactions_history_longInputBindsArray();
BindsArray<OutputCType> events_transactions_history_longOutputBindsArray();

BindsArray<InputCType> events_transactions_summary_by_account_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_transactions_summary_by_account_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_transactions_summary_by_host_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_transactions_summary_by_host_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_transactions_summary_by_thread_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_transactions_summary_by_thread_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_transactions_summary_by_user_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_transactions_summary_by_user_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_transactions_summary_global_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_transactions_summary_global_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_waits_currentInputBindsArray();
BindsArray<OutputCType> events_waits_currentOutputBindsArray();

BindsArray<InputCType> events_waits_historyInputBindsArray();
BindsArray<OutputCType> events_waits_historyOutputBindsArray();

BindsArray<InputCType> events_waits_history_longInputBindsArray();
BindsArray<OutputCType> events_waits_history_longOutputBindsArray();

BindsArray<InputCType> events_waits_summary_by_account_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_waits_summary_by_account_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_waits_summary_by_host_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_waits_summary_by_host_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_waits_summary_by_instanceInputBindsArray();
BindsArray<OutputCType> events_waits_summary_by_instanceOutputBindsArray();

BindsArray<InputCType> events_waits_summary_by_thread_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_waits_summary_by_thread_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_waits_summary_by_user_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_waits_summary_by_user_by_event_nameOutputBindsArray();

BindsArray<InputCType> events_waits_summary_global_by_event_nameInputBindsArray();
BindsArray<OutputCType> events_waits_summary_global_by_event_nameOutputBindsArray();

BindsArray<InputCType> file_instancesInputBindsArray();
BindsArray<OutputCType> file_instancesOutputBindsArray();

BindsArray<InputCType> file_summary_by_event_nameInputBindsArray();
BindsArray<OutputCType> file_summary_by_event_nameOutputBindsArray();

BindsArray<InputCType> file_summary_by_instanceInputBindsArray();
BindsArray<OutputCType> file_summary_by_instanceOutputBindsArray();

BindsArray<InputCType> global_statusInputBindsArray();
BindsArray<OutputCType> global_statusOutputBindsArray();

BindsArray<InputCType> host_cacheInputBindsArray();
BindsArray<OutputCType> host_cacheOutputBindsArray();

BindsArray<InputCType> hostsInputBindsArray();
BindsArray<OutputCType> hostsOutputBindsArray();

BindsArray<InputCType> memory_summary_by_account_by_event_nameInputBindsArray();
BindsArray<OutputCType> memory_summary_by_account_by_event_nameOutputBindsArray();

BindsArray<InputCType> memory_summary_by_host_by_event_nameInputBindsArray();
BindsArray<OutputCType> memory_summary_by_host_by_event_nameOutputBindsArray();

BindsArray<InputCType> memory_summary_by_thread_by_event_nameInputBindsArray();
BindsArray<OutputCType> memory_summary_by_thread_by_event_nameOutputBindsArray();

BindsArray<InputCType> memory_summary_by_user_by_event_nameInputBindsArray();
BindsArray<OutputCType> memory_summary_by_user_by_event_nameOutputBindsArray();

BindsArray<InputCType> memory_summary_global_by_event_nameInputBindsArray();
BindsArray<OutputCType> memory_summary_global_by_event_nameOutputBindsArray();

BindsArray<InputCType> metadata_locksInputBindsArray();
BindsArray<OutputCType> metadata_locksOutputBindsArray();

BindsArray<InputCType> mutex_instancesInputBindsArray();
BindsArray<OutputCType> mutex_instancesOutputBindsArray();

BindsArray<InputCType> objects_summary_global_by_typeInputBindsArray();
BindsArray<OutputCType> objects_summary_global_by_typeOutputBindsArray();

BindsArray<InputCType> performance_timersInputBindsArray();
BindsArray<OutputCType> performance_timersOutputBindsArray();

BindsArray<InputCType> prepared_statements_instancesInputBindsArray();
BindsArray<OutputCType> prepared_statements_instancesOutputBindsArray();

BindsArray<InputCType> replication_applier_configurationInputBindsArray();
BindsArray<OutputCType> replication_applier_configurationOutputBindsArray();

BindsArray<InputCType> replication_applier_statusInputBindsArray();
BindsArray<OutputCType> replication_applier_statusOutputBindsArray();

BindsArray<InputCType> replication_applier_status_by_coordinatorInputBindsArray();
BindsArray<OutputCType> replication_applier_status_by_coordinatorOutputBindsArray();

BindsArray<InputCType> replication_connection_configurationInputBindsArray();
BindsArray<OutputCType> replication_connection_configurationOutputBindsArray();

BindsArray<InputCType> rwlock_instancesInputBindsArray();
BindsArray<OutputCType> rwlock_instancesOutputBindsArray();

BindsArray<InputCType> session_account_connect_attrsInputBindsArray();
BindsArray<OutputCType> session_account_connect_attrsOutputBindsArray();

BindsArray<InputCType> session_connect_attrsInputBindsArray();
BindsArray<OutputCType> session_connect_attrsOutputBindsArray();

BindsArray<InputCType> session_statusInputBindsArray();
BindsArray<OutputCType> session_statusOutputBindsArray();

BindsArray<InputCType> setup_actorsInputBindsArray();
BindsArray<OutputCType> setup_actorsOutputBindsArray();

BindsArray<InputCType> setup_consumersInputBindsArray();
BindsArray<OutputCType> setup_consumersOutputBindsArray();

BindsArray<InputCType> setup_instrumentsInputBindsArray();
BindsArray<OutputCType> setup_instrumentsOutputBindsArray();

BindsArray<InputCType> setup_objectsInputBindsArray();
BindsArray<OutputCType> setup_objectsOutputBindsArray();

BindsArray<InputCType> setup_timersInputBindsArray();
BindsArray<OutputCType> setup_timersOutputBindsArray();

BindsArray<InputCType> socket_instancesInputBindsArray();
BindsArray<OutputCType> socket_instancesOutputBindsArray();

BindsArray<InputCType> socket_summary_by_event_nameInputBindsArray();
BindsArray<OutputCType> socket_summary_by_event_nameOutputBindsArray();

BindsArray<InputCType> socket_summary_by_instanceInputBindsArray();
BindsArray<OutputCType> socket_summary_by_instanceOutputBindsArray();

BindsArray<InputCType> status_by_accountInputBindsArray();
BindsArray<OutputCType> status_by_accountOutputBindsArray();

BindsArray<InputCType> status_by_hostInputBindsArray();
BindsArray<OutputCType> status_by_hostOutputBindsArray();

BindsArray<InputCType> status_by_threadInputBindsArray();
BindsArray<OutputCType> status_by_threadOutputBindsArray();

BindsArray<InputCType> status_by_userInputBindsArray();
BindsArray<OutputCType> status_by_userOutputBindsArray();

BindsArray<InputCType> table_handlesInputBindsArray();
BindsArray<OutputCType> table_handlesOutputBindsArray();

BindsArray<InputCType> table_io_waits_summary_by_index_usageInputBindsArray();
BindsArray<OutputCType> table_io_waits_summary_by_index_usageOutputBindsArray();

BindsArray<InputCType> table_io_waits_summary_by_tableInputBindsArray();
BindsArray<OutputCType> table_io_waits_summary_by_tableOutputBindsArray();

BindsArray<InputCType> table_lock_waits_summary_by_tableInputBindsArray();
BindsArray<OutputCType> table_lock_waits_summary_by_tableOutputBindsArray();

BindsArray<InputCType> threadsInputBindsArray();
BindsArray<OutputCType> threadsOutputBindsArray();

BindsArray<InputCType> user_variables_by_threadInputBindsArray();
BindsArray<OutputCType> user_variables_by_threadOutputBindsArray();

BindsArray<InputCType> usersInputBindsArray();
BindsArray<OutputCType> usersOutputBindsArray();

#endif  // INCLUDED_PERFORMANCE_SCHEMABINDS_H
