// This file was generated by createDBTableBinds() function
#include "giraffeBinds.h"

using namespace seth_ql;

BindsArray<InputCType> branchInputBindsArray() {
   return makeInputBindsArray( Bind<INT>( "branch_id" ), Bind<VARCHAR>( "branch_name", 100 ),
                               Bind<INT>( "mgr_id" ), Bind<DATE>( "mgr_start_date" ) );
}
BindsArray<OutputCType> branchOutputBindsArray() {
   return makeOutputBindsArray( Bind<INT>( "branch_id" ), Bind<VARCHAR>( "branch_name", 100 ),
                                Bind<INT>( "mgr_id" ), Bind<DATE>( "mgr_start_date" ) );
}

BindsArray<InputCType> branch_supplierInputBindsArray() {
   return makeInputBindsArray( Bind<INT>( "branch_id" ), Bind<VARCHAR>( "supplier_name", 100 ),
                               Bind<VARCHAR>( "supply_type", 100 ) );
}
BindsArray<OutputCType> branch_supplierOutputBindsArray() {
   return makeOutputBindsArray( Bind<INT>( "branch_id" ), Bind<VARCHAR>( "supplier_name", 100 ),
                                Bind<VARCHAR>( "supply_type", 100 ) );
}

BindsArray<InputCType> clientInputBindsArray() {
   return makeInputBindsArray( Bind<INT>( "client_id" ), Bind<VARCHAR>( "client_name", 100 ),
                               Bind<INT>( "branch_id" ) );
}
BindsArray<OutputCType> clientOutputBindsArray() {
   return makeOutputBindsArray( Bind<INT>( "client_id" ), Bind<VARCHAR>( "client_name", 100 ),
                                Bind<INT>( "branch_id" ) );
}

BindsArray<InputCType> employeeInputBindsArray() {
   return makeInputBindsArray( Bind<INT>( "emp_id" ), Bind<VARCHAR>( "first_name", 100 ),
                               Bind<VARCHAR>( "last_name", 100 ), Bind<DATE>( "birth_day" ),
                               Bind<VARCHAR>( "sex", 100 ), Bind<INT>( "salary" ),
                               Bind<INT>( "super_id" ), Bind<INT>( "branch_id" ) );
}
BindsArray<OutputCType> employeeOutputBindsArray() {
   return makeOutputBindsArray( Bind<INT>( "emp_id" ), Bind<VARCHAR>( "first_name", 100 ),
                                Bind<VARCHAR>( "last_name", 100 ), Bind<DATE>( "birth_day" ),
                                Bind<VARCHAR>( "sex", 100 ), Bind<INT>( "salary" ),
                                Bind<INT>( "super_id" ), Bind<INT>( "branch_id" ) );
}

BindsArray<InputCType> works_withInputBindsArray() {
   return makeInputBindsArray( Bind<INT>( "emp_id" ), Bind<INT>( "client_id" ),
                               Bind<INT>( "total_sales" ) );
}
BindsArray<OutputCType> works_withOutputBindsArray() {
   return makeOutputBindsArray( Bind<INT>( "emp_id" ), Bind<INT>( "client_id" ),
                                Bind<INT>( "total_sales" ) );
}
