// This file was generated by createDBTableBinds() function
// using the test database from insert_photos.cpp and prep_stmts.cpp in example_code folder

#include "seth_qlBinds.h"

#include "makeBinds.hpp"

using namespace seth_ql;

BindsArray<InputCType> image_tableInputBindsArray() {
   return makeInputBindsArray( Bind<Field::CHAR>( "name" ), Bind<Field::MEDIUMBLOB>( "image" ) );
}
BindsArray<OutputCType> image_tableOutputBindsArray() {
   return makeOutputBindsArray( Bind<Field::CHAR>( "name" ), Bind<Field::MEDIUMBLOB>( "image" ) );
}

BindsArray<InputCType> test_tableInputBindsArray() {
   return makeInputBindsArray( Bind<Field::INT>( "emp_id" ), Bind<Field::VARCHAR>( "name" ),
                               Bind<Field::VARCHAR>( "role" ), Bind<Field::INT>( "site_id" ) );
}
BindsArray<OutputCType> test_tableOutputBindsArray() {
   return makeOutputBindsArray( Bind<Field::INT>( "emp_id" ), Bind<Field::VARCHAR>( "name" ),
                                Bind<Field::VARCHAR>( "role" ), Bind<Field::INT>( "site_id" ) );
}
