// This file was generated by createDBTableBinds() function
// using the test database from insert_photos.cpp and prep_stmts.cpp in example_code folder

#ifndef INCLUDED_SETH_QLBINDS_H
#define INCLUDED_SETH_QLBINDS_H

#include "BindsArray.hpp"
#include "makeBinds.hpp"

using namespace seth_ql;


BindsArray<InputCType> image_tableInputBindsArray();
BindsArray<OutputCType> image_tableOutputBindsArray();

BindsArray<InputCType> test_tableInputBindsArray();
BindsArray<OutputCType> test_tableOutputBindsArray();


#endif //INCLUDED_SETH_QLBINDS_H
